# Generated by Django 4.2.15 on 2025-07-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=12, verbose_name="OTP"),
        ),
    ]
