# Generated by Django 4.2.15 on 2025-07-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_alter_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=128, verbose_name="OTP"),
        ),
    ]
